name: "Pull Request Summary"
description: "Generate a summary for pull requests using OpenAI API"
author: "Joacim Magnusson"
inputs:
  token:
    description: "GitHub token"
    required: true
  openaiApiKey:
    description: "OpenAI API key"
    required: true
runs:
  using: "node18"
  main: "generateSummary.mjs"
