name: "Pull Request Summary"
description: "Generate a summary for pull requests using OpenAI API"
author: "Joacim Magnusson"
inputs:
  token:
    description: "GitHub token"
    required: true
  openaiApiKey:
    description: "OpenAI API key"
    required: true
  openaiOrgId:
    description: "OpenAI Organization ID"
    required: true
  githubEvent:
    description: "GitHub webhook event"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_EVENT: ${{ inputs.githubEvent }}
    GITHUB_TOKEN: ${{ inputs.token }}
    OPENAI_API_KEY: ${{ inputs.openaiApiKey }}
    OPENAI_ORG_ID: ${{ inputs.openaiOrgId }}
